/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-07 09:05:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.analyse.dataAnalyse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sinaSource_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>新闻来源分析</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- 这里用requirejs来做模块加载器 -->\r\n");
      out.write("    <script src=\"http://requirejs.org/docs/release/2.1.20/minified/require.js\"></script>\r\n");
      out.write("    <!-- Chartx图表库文件引入，这里已1.9.21的cdn版本为例 -->\r\n");
      out.write("    <script src=\"http://g.tbcdn.cn/thx/charts/1.9.51/chartx/index-min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("    <span>\r\n");
      out.write("        <h3>新闻来源访问量分析</h3>\r\n");
      out.write("         <h3>热门新闻来源访问量Top30</h3>\r\n");
      out.write("    </span>\r\n");
      out.write("    <div id=\"techTest\" style=\"width:1100px;height:950px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var data = [\r\n");
      out.write("        [\"xfield\", \"percent\"],\r\n");
      out.write("//        [\"重庆时报网\", 1],\r\n");
      out.write("//        [\"重庆时报\",1],\r\n");
      out.write("//        [\"重庆商报\",1],\r\n");
      out.write("//        [\"重庆日报\",1],\r\n");
      out.write("//        [\"重庆晨报\", 1],\r\n");
      out.write("//        [\"中央纪委监察部网站\", 1],\r\n");
      out.write("//        [\"中青在线\", 1],\r\n");
      out.write("//        [\"中国政府网\",1],\r\n");
      out.write("//        [\"中国证券报-中证网\", 2],\r\n");
      out.write("//        [\"中国新闻网\", 2],\r\n");
      out.write("//\r\n");
      out.write("//        [\"中国天气网\", 2],\r\n");
      out.write("//        [\"中国日报\", 2],\r\n");
      out.write("//        [\"中国青年报\", 2],\r\n");
      out.write("//        [\"中国经济周刊\", 3],\r\n");
      out.write("//        [\"中国经济网\", 5],\r\n");
      out.write("//        [\"中国地震局网站\", 7],\r\n");
      out.write("//        [\"中工网\", 7],\r\n");
      out.write("//        [\"政府网站\", 9],\r\n");
      out.write("//        [\"证券日报\", 9],\r\n");
      out.write("//        [\"长安剑\", 13],\r\n");
      out.write("//\r\n");
      out.write("//        [\"云南网\", 19],\r\n");
      out.write("//        [\"银川日报\", 20],\r\n");
      out.write("//        [\"央视财经\", 20],\r\n");
      out.write("//        [\"央广网\", 26],\r\n");
      out.write("//        [\"新浪综合\", 27],\r\n");
      out.write("//        [\"新京报\", 29],\r\n");
      out.write("//        [\"新华网\", 60],\r\n");
      out.write("//        [\"新华视点\", 63],\r\n");
      out.write("//        [\"新华社\", 66],\r\n");
      out.write("//        [\"现代快报\", 93],\r\n");
      out.write("//\r\n");
      out.write("//        [\"外交部网站\", 95],\r\n");
      out.write("//        [\"四川省人民政府网站\", 95],\r\n");
      out.write("//        [\"司法部网站\", 109],\r\n");
      out.write("//        [\"食药监总局\",121],\r\n");
      out.write("//        [\"十九大新闻中心\", 172],\r\n");
      out.write("//        [\"商务部网站\", 192],\r\n");
      out.write("//        [\"陕西省人民政府网站\", 214],\r\n");
      out.write("//        [\"人民日报中央厨房\", 220],\r\n");
      out.write("//        [\"人民日报海外版-海外网\", 222],\r\n");
      out.write("//        [\"澎湃新闻\", 224],\r\n");
      out.write("\r\n");
      out.write("        [\"南方日报\", 235],\r\n");
      out.write("        [\"每日经济新闻\", 304],\r\n");
      out.write("        [\"昆明日报\", 328],\r\n");
      out.write("        [\"科技日报\", 335],\r\n");
      out.write("        [\"看看新闻KNEWS\", 378],\r\n");
      out.write("        [\"军报记者\", 415],\r\n");
      out.write("        [\"经济日报\", 717],\r\n");
      out.write("        [\"经济参考报\", 846],\r\n");
      out.write("        [\"解放日报\", 1036],\r\n");
      out.write("        [\"环球网\", 1155],\r\n");
      out.write("\r\n");
      out.write("        [\"环球时报\", 1361],\r\n");
      out.write("        [\"华声在线-湖南日报\", 1579],\r\n");
      out.write("        [\"华商网\", 1636],\r\n");
      out.write("        [\"华商晨报\", 1986],\r\n");
      out.write("        [\"华商报\", 2470],\r\n");
      out.write("        [\"华龙网\", 2542],\r\n");
      out.write("        [\"湖北日报网\", 3563],\r\n");
      out.write("        [\"国防部网站\", 4143],\r\n");
      out.write("        [\"贵阳网\", 4480],\r\n");
      out.write("        [\"工人日报\", 4666],\r\n");
      out.write("\r\n");
      out.write("        [\"法制晚报网\", 4986],\r\n");
      out.write("        [\"法制晚报\", 6630],\r\n");
      out.write("        [\"法律与生活杂志\", 8154],\r\n");
      out.write("        [\"大洋网-广州日报\", 10166],\r\n");
      out.write("        [\"大洋网\", 10661],\r\n");
      out.write("        [\"成都商报\", 15866],\r\n");
      out.write("        [\"参考消息\", 17102],\r\n");
      out.write("        [\"北京时间\", 21804],\r\n");
      out.write("        [\"21世纪经济报道\", 43805]\r\n");
      out.write("\r\n");
      out.write("    ];\r\n");
      out.write("    var options = {\r\n");
      out.write("        type: \"horizontal\",\r\n");
      out.write("        yAxis: {\r\n");
      out.write("            field: [\"percent\"]\r\n");
      out.write("        },\r\n");
      out.write("        xAxis: {\r\n");
      out.write("            field: [\"xfield\"]\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    Chartx.bar(\"techTest\", data, options);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
