/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-07 09:05:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.analyse.dataAnalyse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sinaTime_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>新闻时间点击率分析</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- 这里用requirejs来做模块加载器 -->\r\n");
      out.write("    <script src=\"http://requirejs.org/docs/release/2.1.20/minified/require.js\"></script>\r\n");
      out.write("    <!-- Chartx图表库文件引入，这里已1.9.21的cdn版本为例 -->\r\n");
      out.write("    <script src=\"http://g.tbcdn.cn/thx/charts/1.9.51/chartx/index-min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("    <h3>新闻时间点击率分析</h3>\r\n");
      out.write("\r\n");
      out.write("<div id=\"allTest\" style=\"width:1200px;height:600px;\"></div>\r\n");
      out.write("    <h3>2017年10月10日热门新闻来源访问率</h3>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"techTest\" style=\"width:1200px;height:650px;\"></div>\r\n");
      out.write("    <h3>2017年10月11日热门新闻来源访问率</h3>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"dataTest\" style=\"width:1200px;height:600px;\"></div>\r\n");
      out.write("    <h3>2017年10月12日热门新闻来源访问率</h3>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"bigTest\" style=\"width:1200px;height:600px;\"></div>\r\n");
      out.write("    <h3>2017年10月13日热门新闻来源访问率</h3>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"dateTest\" style=\"width:1200px;height:300px;\"></div>\r\n");
      out.write("    <h3>2017年10月23日热门新闻来源访问率</h3>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"finaTest\" style=\"width:1200px;height:600px;\"></div>\r\n");
      out.write("    <h3>2017年10月24日热门新闻来源访问率</h3>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <script>\r\n");
      out.write("    var data = [\r\n");
      out.write("\r\n");
      out.write("        [\"xfield\", \"percent\"],\r\n");
      out.write("        [\"中国经济网\", 1662],\r\n");
      out.write("        [\"法制晚报\", 1431],\r\n");
      out.write("        [\"澎湃新闻\", 1078],\r\n");
      out.write("        [\"法律与生活杂志\", 627],\r\n");
      out.write("        [\"新浪综合\", 233],\r\n");
      out.write("        [\"参考消息\", 144],\r\n");
      out.write("        [\"成都商报\", 121],\r\n");
      out.write("        [\"环球时报\", 36],\r\n");
      out.write("        [\"央广网\", 35],\r\n");
      out.write("        [\"军报记者\", 20],\r\n");
      out.write("        [\"人民日报海外版-海外网\",10],\r\n");
      out.write("        [\"中国新闻网\", 8],\r\n");
      out.write("        [\"央视新闻\", 5],\r\n");
      out.write("        [\"中央纪委监察部网站\", 3],\r\n");
      out.write("        [\"环球网\", 3],\r\n");
      out.write("        [\"新华社\",1]\r\n");
      out.write("    ];\r\n");
      out.write("    var options = {\r\n");
      out.write("        type: \"horizontal\",\r\n");
      out.write("        yAxis: {\r\n");
      out.write("            field: [\"percent\"]\r\n");
      out.write("        },\r\n");
      out.write("        xAxis: {\r\n");
      out.write("            field: [\"xfield\"]\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    Chartx.bar(\"allTest\", data, options);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        var data = [\r\n");
      out.write("\r\n");
      out.write("            [\"xfield\", \"percent\"], [\"央视财经\", 14869], [\"澎湃新闻\", 12240], [\"参考消息\", 8815], [\"中青在线\", 4981], [\"中国新闻网\", 4925],\r\n");
      out.write("            [\"长安剑\", 4635], [\"人民日报海外版-海外网\", 3520], [\"北京时间\", 2246], [\"新京报\", 2156], [\"中国经济网\", 1898],\r\n");
      out.write("            [\"环球网\",1096], [\"中国政府网\", 1029], [\"法律与生活杂志\", 607], [\"新华社\", 548], [\"经济参考报\", 535],\r\n");
      out.write("            [\"中国青年报\",370], [\"中国之声\", 369], [\"央视新闻\",275], [\"司法部网站\", 224],\r\n");
      out.write("            [\"新华视点\",192]\r\n");
      out.write("//            [\"大洋网\", 172],\r\n");
      out.write("//            [\"云南网\",93],[\"解放日报\", 79],\r\n");
      out.write("//            [\"法制晚报\",64],[\"21世纪经济报道\", 62],\r\n");
      out.write("//            [\"环球时报\",51],[\"昆明日报\", 27],\r\n");
      out.write("//            [\"人民日报中央厨房\",19],[\"重庆时报网\", 13],\r\n");
      out.write("//            [\"每日经济新闻\",9],[\"中央纪委监察部网站\", 8],\r\n");
      out.write("//            [\"央广网\",3],[\"政府网站\", 3], [\"中国天气网\",3],[\"十九大新闻中心\", 2],\r\n");
      out.write("//            [\"国防部网站\",1], [\"科技日报\",1], [\"四川省人民政府网站\",1],  [\"中工网\",1]\r\n");
      out.write("\r\n");
      out.write("        ];\r\n");
      out.write("        var options = {\r\n");
      out.write("            type: \"horizontal\",\r\n");
      out.write("            yAxis: {\r\n");
      out.write("                field: [\"percent\"]\r\n");
      out.write("            },\r\n");
      out.write("            xAxis: {\r\n");
      out.write("                field: [\"xfield\"]\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        Chartx.bar(\"techTest\", data, options);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        var data = [\r\n");
      out.write("\r\n");
      out.write("            [\"xfield\", \"percent\"],\r\n");
      out.write("            [\"澎湃新闻\", 24005], [\"工人日报\", 10166], [\"中国新闻网\", 8178],\r\n");
      out.write("            [\"人民日报海外版-海外网\", 1613], [\"央视新闻\", 1397], [\"新京报\", 1272],\r\n");
      out.write("            [\"华商报\", 710], [\"参考消息\", 664], [\"现代快报\", 304],\r\n");
      out.write("            [\"环球时报\", 241], [\"华龙网\",206], [\"新华社\", 126],\r\n");
      out.write("            [\"中国青年报\", 96], [\"大洋网-广州日报\", 89], [\"中国日报\", 66],\r\n");
      out.write("            [\"环球网\",62], [\"中国地震局网站\", 54], [\"解放日报\",40],\r\n");
      out.write("            [\"经济日报\", 26], [\"重庆时报\",18]\r\n");
      out.write("//            [\"政府网站\", 13],\r\n");
      out.write("//            [\"央广网\",10],[\"新华网\", 9], [\"中国政府网\",6],\r\n");
      out.write("//            [\"法律与生活杂志\", 2], [\"华商网\",2],[\"新浪综合\", 2],\r\n");
      out.write("//            [\"银川日报\",2],[\"中国经济网\", 2], [\"南方日报\",1]\r\n");
      out.write("\r\n");
      out.write("        ];\r\n");
      out.write("        var options = {\r\n");
      out.write("            type: \"horizontal\",\r\n");
      out.write("            yAxis: {\r\n");
      out.write("                field: [\"percent\"]\r\n");
      out.write("            },\r\n");
      out.write("            xAxis: {\r\n");
      out.write("                field: [\"xfield\"]\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        Chartx.bar(\"dataTest\", data, options);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        var data = [\r\n");
      out.write("\r\n");
      out.write("            [\"xfield\", \"percent\"],\r\n");
      out.write("            [\"外交部网站\", 8154], [\"人民日报海外版-海外网\", 5518], [\"澎湃新闻\", 5424],\r\n");
      out.write("            [\"法制晚报\", 2985], [\"解放日报\", 2423], [\"中国新闻网\", 2167],\r\n");
      out.write("            [\"央广网\", 1874], [\"经济参考报\", 1451], [\"国防部网站\", 1360],\r\n");
      out.write("            [\"央视新闻\", 628], [\"新华社\",480], [\"参考消息\", 456],\r\n");
      out.write("\r\n");
      out.write("            [\"法律与生活杂志\", 437], [\"中国证券报-中证网\", 415],\r\n");
      out.write("            [\"新京报\",379], [\"中央纪委监察部网站\", 367], [\"华商网\",213],\r\n");
      out.write("            [\"重庆时报\", 204], [\"环球网\",139],[\"湖北日报网\", 95]\r\n");
      out.write("\r\n");
      out.write("//            [\"重庆日报\",66],[\"中国日报\", 53], [\"长安剑\",31],\r\n");
      out.write("//            [\"贵阳网\", 7], [\"商务部网站\",7],[\"大洋网-广州日报\", 6],\r\n");
      out.write("//            [\"中青在线\",5],[\"科技日报\", 4], [\"中国青年报\",3],\r\n");
      out.write("//            [\"法制晚报网\",2],[\"证券日报\", 2], [\"重庆商报\",2],\r\n");
      out.write("//            [\"21世纪经济报道\",1],[\"食药监总局\", 1], [\"中国地震局网站\",1],\r\n");
      out.write("//            [\"中国经济网\",1],[\"重庆晨报\", 1]\r\n");
      out.write("        ];\r\n");
      out.write("        var options = {\r\n");
      out.write("            type: \"horizontal\",\r\n");
      out.write("            yAxis: {\r\n");
      out.write("                field: [\"percent\"]\r\n");
      out.write("            },\r\n");
      out.write("            xAxis: {\r\n");
      out.write("                field: [\"xfield\"]\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        Chartx.bar(\"bigTest\", data, options);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        var data = [\r\n");
      out.write("\r\n");
      out.write("            [\"xfield\", \"percent\"],\r\n");
      out.write("            [\"北京时间\", 224], [\"看看新闻KNEWS\", 214], [\"澎湃新闻\", 88],\r\n");
      out.write("            [\"华商报\", 3], [\"华声在线-湖南日报\", 1], [\"中国新闻网\", 1]\r\n");
      out.write("\r\n");
      out.write("           ];\r\n");
      out.write("        var options = {\r\n");
      out.write("            type: \"horizontal\",\r\n");
      out.write("            yAxis: {\r\n");
      out.write("                field: [\"percent\"]\r\n");
      out.write("            },\r\n");
      out.write("            xAxis: {\r\n");
      out.write("                field: [\"xfield\"]\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        Chartx.bar(\"dateTest\", data, options);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        var data = [\r\n");
      out.write("\r\n");
      out.write("                [\"xfield\", \"percent\"],\r\n");
      out.write("            [\"参考消息\", 11705], [\"央广网\", 4708], [\"澎湃新闻\", 970],\r\n");
      out.write("            [\"中国新闻网\", 579], [\"中国青年报\", 377], [\"环球网\", 336],\r\n");
      out.write("            [\"新京报\", 334], [\"华龙网\", 129], [\"华商晨报\", 29],\r\n");
      out.write("            [\"华商网\", 5], [\"华商报\", 4], [\"政府网站\", 4],\r\n");
      out.write("            [\"中国地震局网站\", 4], [\"陕西省人民政府网站\", 1], [\"央视新闻\", 1],\r\n");
      out.write("            [\"中国经济周刊\", 1], [\"中国政府网\", 1]\r\n");
      out.write("        ];\r\n");
      out.write("        var options = {\r\n");
      out.write("            type: \"horizontal\",\r\n");
      out.write("            yAxis: {\r\n");
      out.write("                field: [\"percent\"]\r\n");
      out.write("            },\r\n");
      out.write("            xAxis: {\r\n");
      out.write("                field: [\"xfield\"]\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        Chartx.bar(\"finaTest\", data, options);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
