/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-07 09:05:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.analyse.dataAnalyse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class wangEditor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>热门新闻作者访问分析</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- 这里用requirejs来做模块加载器 -->\r\n");
      out.write("    <script src=\"http://requirejs.org/docs/release/2.1.20/minified/require.js\"></script>\r\n");
      out.write("    <!-- Chartx图表库文件引入，这里已1.9.21的cdn版本为例 -->\r\n");
      out.write("    <script src=\"http://g.tbcdn.cn/thx/charts/1.9.51/chartx/index-min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\" >\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- 为Chartx准备一个具备大小（宽高）的Dom -->\r\n");
      out.write("    <h2 >热门新闻作者访问分析</h2>\r\n");
      out.write("    <br>\r\n");
      out.write("    <h3>热门新闻作者访问量Top20</h3>\r\n");
      out.write("    <br>\r\n");
      out.write("<div id=\"allTest\" style=\"width:1100px;height:800px;\">\r\n");
      out.write("</div>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    var data = [\r\n");
      out.write("    [\"xfield\", \"percent\"],\r\n");
      out.write("    [\"李旭朝\", 730999],\r\n");
      out.write("    [\"俞诗瑜\",481549],\r\n");
      out.write("    [\"谷莹\",382299],\r\n");
      out.write("    [\"马婧雯\",314028],\r\n");
      out.write("    [\"杨易颖\", 191540],\r\n");
      out.write("    [\"张洋洋\", 126950],\r\n");
      out.write("    [\"郑鸿豪\", 83777],\r\n");
      out.write("    [\"仝贺\",69271],\r\n");
      out.write("    [\"朱楷正\", 52399],\r\n");
      out.write("    [\"陈恺\", 42477],\r\n");
      out.write("\r\n");
      out.write("    [\"马路遥\", 41774],\r\n");
      out.write("    [\"彭惠智\", 40617],\r\n");
      out.write("    [\"黄哲程\", 32927],\r\n");
      out.write("    [\"姚成浩\", 28655],\r\n");
      out.write("    [\"张腾\", 27984],\r\n");
      out.write("    [\"乔敬\", 23399],\r\n");
      out.write("    [\"李彤\", 14883],\r\n");
      out.write("    [\"赵亮亮\", 14721],\r\n");
      out.write("    [\"杨雯婕\", 13950],\r\n");
      out.write("    [\"王征\", 12962]\r\n");
      out.write("\r\n");
      out.write("    ];\r\n");
      out.write("    var options = {\r\n");
      out.write("    type: \"horizontal\",\r\n");
      out.write("    yAxis: {\r\n");
      out.write("    field: [\"percent\"],\r\n");
      out.write("        label: \"访问量\"\r\n");
      out.write("    },\r\n");
      out.write("    xAxis: {\r\n");
      out.write("    field: [\"xfield\"],\r\n");
      out.write("    label: \"热门新闻作者\"\r\n");
      out.write("    }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    Chartx.bar(\"allTest\", data, options);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
