/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-07 13:01:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.analyse.dataAnalyse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wangSource_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>热门新闻来源分析</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- 这里用requirejs来做模块加载器 -->\r\n");
      out.write("    <script src=\"http://requirejs.org/docs/release/2.1.20/minified/require.js\"></script>\r\n");
      out.write("    <!-- Chartx图表库文件引入，这里已1.9.21的cdn版本为例 -->\r\n");
      out.write("    <script src=\"http://g.tbcdn.cn/thx/charts/1.9.51/chartx/index-min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/analyse/common/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("    <span>\r\n");
      out.write("        <h2>新闻来源访问量分析</h2>\r\n");
      out.write("        <h3>热门新闻来源访问Top30</h3>\r\n");
      out.write("    </span>\r\n");
      out.write("    <div id=\"techTest\" style=\"width:1000px;height:900px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var data = [\r\n");
      out.write("\r\n");
      out.write("            [\"xfield\", \"percent\"],\r\n");
      out.write("        [\"大河网\", 272477],\r\n");
      out.write("        [\"北青网-北京青年报\",241020],\r\n");
      out.write("        [\"澎湃新闻网\",237679],\r\n");
      out.write("        [\"央广网\",198707],\r\n");
      out.write("        [\"中国江苏网\", 187593],\r\n");
      out.write("        [\"新华网\", 153230],\r\n");
      out.write("        [\"网易体育\", 145157],\r\n");
      out.write("        [\"中国新闻网\",128974],\r\n");
      out.write("        [\"重庆晨报\", 125067],\r\n");
      out.write("        [\"乐清日报\", 124729],\r\n");
      out.write("\r\n");
      out.write("        [\"荆楚网\", 113759],\r\n");
      out.write("        [\"环球时报-环球网\", 113400],\r\n");
      out.write("        [\"钱江晚报\", 98166],\r\n");
      out.write("        [\"网易娱乐\", 89346],\r\n");
      out.write("        [\"21世纪经济报道\", 64799],\r\n");
      out.write("        [\"新京报\", 64017],\r\n");
      out.write("        [\"财经网\", 41150],\r\n");
      out.write("        [\"中国日报网\", 35781],\r\n");
      out.write("        [\"现代金报\", 32899],\r\n");
      out.write("        [\"中国台湾网\", 31715],\r\n");
      out.write("\r\n");
      out.write("        [\"肆客足球APP\", 29628],\r\n");
      out.write("        [\"新京报即时新闻\", 27316],\r\n");
      out.write("        [\"法制晚报\", 16482],\r\n");
      out.write("        [\"东方网\", 16291],\r\n");
      out.write("        [\"重案组37号\", 15846],\r\n");
      out.write("        [\"现代快报\", 15545],\r\n");
      out.write("        [\"成都商报\", 13059],\r\n");
      out.write("        [\"华商报\", 12716],\r\n");
      out.write("        [\"观海解局\", 12354],\r\n");
      out.write("        [\"荆楚网-楚天都市报\", 12024]\r\n");
      out.write("\r\n");
      out.write("    ];\r\n");
      out.write("    var options = {\r\n");
      out.write("        type: \"horizontal\",\r\n");
      out.write("        yAxis: {\r\n");
      out.write("            field: [\"percent\"],\r\n");
      out.write("            label: \"访问量\"\r\n");
      out.write("        },\r\n");
      out.write("        xAxis: {\r\n");
      out.write("            field: [\"xfield\"],\r\n");
      out.write("            label: \"热门新闻来源\"\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    Chartx.bar(\"techTest\", data, options);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
