/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-10-12 03:09:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>新用户注册</title>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"place\">\r\n");
      out.write("    <span>位置：</span>\r\n");
      out.write("    <ul class=\"placeul\">\r\n");
      out.write("    <li><a href=\"#\">首页</a></li>\r\n");
      out.write("    <li><a href=\"#\">表单</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"formbody\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"formtitle\"><span>用户注册</span></div>\r\n");
      out.write("    <form action=\"userAdd_success.jsp\" method=\"post\">\r\n");
      out.write("    <ul class=\"forminfo\">\r\n");
      out.write("    <li><label>电话号码</label><input name=\"user_phone\" type=\"text\" class=\"dfinput\"></li>\r\n");
      out.write("    <li><label>用户名</label><input name=\"user_name\" type=\"text\" class=\"dfinput\"></li>\r\n");
      out.write("    <li><label>真实姓名</label><input name=\"truename\" type=\"text\" class=\"dfinput\"></li>\r\n");
      out.write("    <li><label>输入密码</label><input name=\"password\" type=\"password\" class=\"dfinput\"></li>\t\r\n");
      out.write("    <li><label>地区</label><select name = \"place\" class=\"dfinput\">\r\n");
      out.write("    \t\t<option value = \"默认\" selected=\"selected\">请选择</option>\r\n");
      out.write("    \t\t<option value = \"北京\">北京市</option>\r\n");
      out.write("    \t\t<option value = \"天津\">天津市</option>\r\n");
      out.write("    \t\t<option value = \"上海\">上海市</option>\r\n");
      out.write("    \t\t<option value = \"重庆\">重庆市</option>\r\n");
      out.write("    \t\t<option value = \"河北\">河北省</option>\r\n");
      out.write("    \t\t<option value = \"河南\">河南省</option>\r\n");
      out.write("    \t\t<option value = \"云南\">云南省</option>\r\n");
      out.write("    \t\t<option value = \"辽宁\">辽宁省</option>\r\n");
      out.write("    \t\t<option value = \"黑龙江\">黑龙江省</option>\r\n");
      out.write("    \t\t<option value = \"湖南\">湖南省</option>\r\n");
      out.write("    \t\t<option value = \"安徽\">安徽省</option>\r\n");
      out.write("    \t\t<option value = \"山东\">山东省</option>\r\n");
      out.write("    \t\t<option value = \"新疆\">新疆维吾尔自治区</option>\r\n");
      out.write("    \t\t<option value = \"江苏\">江苏省</option>\r\n");
      out.write("    \t\t<option value = \"湖北\">湖北省</option>\r\n");
      out.write("    \t\t<option value = \"湖南\">湖南省</option>\r\n");
      out.write("    \t\t<option value = \"浙江\">浙江省</option>\r\n");
      out.write("    \t\t<option value = \"江西\">江西省</option>\r\n");
      out.write("    \t\t<option value = \"广西\">广西壮族自治区</option>\r\n");
      out.write("    \t\t<option value = \"甘肃\">甘肃省</option>\r\n");
      out.write("    \t\t<option value = \"山西\">山西省</option>\r\n");
      out.write("    \t\t<option value = \"陕西\">陕西省</option>\r\n");
      out.write("    \t\t<option value = \"吉林\">吉林省</option>\r\n");
      out.write("    \t\t<option value = \"福建\">福建省</option>\r\n");
      out.write("    \t\t<option value = \"贵州\">贵州省</option>\r\n");
      out.write("    \t\t<option value = \"广东\">广东省</option>\r\n");
      out.write("    \t\t<option value = \"青海\">青海省</option>\r\n");
      out.write("    \t\t<option value = \"西藏\">西藏自治区</option>\r\n");
      out.write("    \t\t<option value = \"四川\">四川省</option>\r\n");
      out.write("    \t\t<option value = \"宁夏\">宁夏回族自治区</option>\r\n");
      out.write("    \t\t<option value = \"海南\">海南省</option>\r\n");
      out.write("    \t</select>\r\n");
      out.write("    \t\t\r\n");
      out.write("    </li>\r\n");
      out.write("    <li><label>&nbsp;</label><input name=\"\" type=\"submit\" class=\"btn\" value=\"提交\"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input  type=\"reset\"  name=\"重置\"  class=\"btn\" value=\"重置\"/></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("   \r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
